FROM node:18-alpine3.16

LABEL version="1"
LABEL description="Angular Frontend for Invoices API"

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli
RUN npm install

COPY . .

EXPOSE 4200
CMD [ "ng", "serve", "--host", "0.0.0.0" ]
