#!/bin/bash 

set -o errexit

set -o nounset 

worker_ready(){
  celery -A invoices_project inspect ping
}

until worker_ready; do
  >&2 echo "Celery workers are not available :-("
  sleep 1

done
>&2 echo "Celery workers are available and ready!... :-)"

celery \
  --app=invoices_project \
  --broker="${CELERY_BROKER}" \
  flower