# Generated by Django 4.1.7 on 2023-03-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientaddress",
            name="post_code",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Post Code"
            ),
        ),
        migrations.AlterField(
            model_name="clientaddress",
            name="street",
            field=models.CharField(blank=True, max_length=255, verbose_name="Street"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_due",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Payment Due Date"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Total Cost",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Item Price",
            ),
        ),
        migrations.AlterField(
            model_name="senderaddress",
            name="post_code",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Post Code"
            ),
        ),
        migrations.AlterField(
            model_name="senderaddress",
            name="street",
            field=models.CharField(blank=True, max_length=255, verbose_name="Street"),
        ),
    ]
