# Generated by Django 4.1.7 on 2023-03-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0002_alter_clientaddress_post_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Total Cost",
            ),
        ),
    ]
