# Generated by Django 4.1.7 on 2023-03-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_item_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_no",
            field=models.CharField(
                blank=True, max_length=6, null=True, verbose_name="Invoice Number"
            ),
        ),
    ]
