# Generated by Django 4.1.7 on 2023-03-17 09:09

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_alter_invoice_invoice_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientaddress",
            name="city",
            field=models.CharField(
                blank=True, default="Nairobi", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="clientaddress",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="KE", max_length=2, verbose_name="Country"
            ),
        ),
        migrations.AlterField(
            model_name="senderaddress",
            name="city",
            field=models.CharField(
                blank=True, default="Nairobi", max_length=180, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="senderaddress",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, default="KE", max_length=2, verbose_name="Country"
            ),
        ),
    ]
